owner: onliseguros # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: API - v1
    url: https://api.onli.com.br/v1
    expectedStatusCodes:
      - 404
  - name: ID
    url: https://id.onli.com.br
    expectedStatusCodes:
      - 200
      - 301
  - name: Manager
    url: https://manager.onli.com.br
    expectedStatusCodes:
      - 200
      - 301
  - name: Website
    url: https://www.onli.com.br
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.onli.com.br
  # baseUrl: /your-repo-name
  logoUrl: https://s3.sa-east-1.amazonaws.com/static.onli.com.br/onli/logo_principal_positivo128.png
  name: Onli Seguros - Status Page
  introTitle: Check the status of our services and APIs.
  introMessage: This page informs the status of our services and APIs, you can use this to check the overall uptime and incident reports.]
  favicon: https://onli.com.br/favicon.ico
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
