owner: onliseguros # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: API - v1
    url: https://api.onli.com.br/v1
    expectedStatusCodes:
      - 404
  - name: Id
    url: https://id.onli.com.br
    expectedStatusCodes:
      - 200
      - 301
  - name: Manager
    url: https://manager.onli.com.br
    expectedStatusCodes:
      - 200
      - 301
  - name: Website
    url: https://www.onli.com.br
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.onli.com.br
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Onli Seguros
  introTitle: Check the status of our services and APIs.
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
